name: Build sources JARs

concurrency: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: cd intermine && ./gradlew install --stacktrace
      - run: mkdir jar_folders && cp -r ~/.m2/repository/org/intermine/* jar_folders
      - uses: actions/upload-artifact@v4
        with:
          name: sources_jars
          path: jar_folders
